---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hubble-ui
  labels:
    k8s-app: hubble-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      labels:
        k8s-app: hubble-ui
    spec:
      serviceAccount: hubble-ui
      serviceAccountName: hubble-ui
      containers:
        - name: frontend
          image: quay.io/cilium/hubble-ui:v0.8.4
          ports:
            - name: http
              containerPort: 8080
        - name: backend
          image: quay.io/cilium/hubble-ui-backend:v0.8.4
          env:
            - name: EVENTS_SERVER_PORT
              value: "8090"
            - name: FLOWS_API_ADDR
              value: "hubble-relay:80"

          ports:
            - name: grpc
              containerPort: 8090
        - name: proxy
          image: docker.io/envoyproxy/envoy:v1.18.4
          ports:
            - name: http
              containerPort: 8081
          command: [envoy]
          args:
            - -c
            - /etc/envoy.yaml
            - -l
            - info
          volumeMounts:
            - name: hubble-ui-envoy-yaml
              mountPath: /etc/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: hubble-ui-envoy-yaml
          configMap:
            name: hubble-ui-envoy
