---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-relay
  labels:
    app.kubernetes.io/name: hubble-relay
    {{- include "hubble-gke-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.relay.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-relay
      {{- include "hubble-gke-exporter.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubble-relay
        {{- include "hubble-gke-exporter.labels" . | nindent 8 }}
    spec:
      containers:
        - name: hubble-relay
          image: "{{ .Values.relay.image.repository }}:v{{ .Chart.AppVersion }}"
          command:
            - hubble-relay
          args:
            - serve
          ports:
            - name: grpc
              containerPort: 4245
          readinessProbe:
            tcpSocket:
              port: grpc
          livenessProbe:
            tcpSocket:
              port: grpc
          volumeMounts:
            - name: hubble-sock-dir
              mountPath: /var/run/cilium
              readOnly: true
            - name: config
              mountPath: /etc/hubble-relay
              readOnly: true
      restartPolicy: Always
      serviceAccount: {{ include "hubble-gke-exporter.fullname" . }}-relay
      serviceAccountName: {{ include "hubble-gke-exporter.fullname" . }}-relay
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 0
      volumes:
        - name: config
          configMap:
            name: {{ include "hubble-gke-exporter.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: hubble-sock-dir
          hostPath:
            path: /var/run/cilium
            type: Directory
