---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: hubble-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubble-ui
    spec:
      serviceAccount: hubble-ui
      serviceAccountName: hubble-ui
      containers:
        - name: frontend
          image: "{{ .Values.ui.frontend.image.repository }}:{{ .Values.ui.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.ui.frontend.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
        - name: backend
          image: "{{ .Values.ui.backend.image.repository }}:{{ .Values.ui.backend.image.tag }}"
          imagePullPolicy: {{ .Values.ui.backend.image.imagePullPolicy }}
          env:
            - name: EVENTS_SERVER_PORT
              value: "8090"
            - name: FLOWS_API_ADDR
              value: "hubble-relay:80"
          ports:
            - name: grpc
              containerPort: 8090
        - name: proxy
          image: "{{ .Values.ui.proxy.image.repository }}:{{ .Values.ui.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.ui.proxy.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8081
          command: 
            - envoy
          args:
            - -c
            - /etc/envoy.yaml
            - -l
            - info
          volumeMounts:
            - name: hubble-ui-envoy-yaml
              mountPath: /etc/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: hubble-ui-envoy-yaml
          configMap:
            name: hubble-ui-envoy
