---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-relay
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - componentstatuses
      - endpoints
      - namespaces
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cilium.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
subjects:
  - kind: ServiceAccount
    name: {{ include "hubble-gke-exporter.fullname" . }}-ui
    namespace: {{ .Release.Namespace }}
