---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: gke-hubble-export
    {{- include "hubble-gke-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.relay.type }}
  selector:
    app.kubernetes.io/name: hubble-relay
  ports:
    - protocol: TCP
      port: {{ .Values.service.relay.port }}
      targetPort: 4245
      name: {{ .Values.service.relay.name }}
